# Generated by Django 4.0.5 on 2022-06-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='job_seeker',
            new_name='jobSeeker_name',
        ),
    ]
