# Generated by Django 4.0.5 on 2022-06-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_job_seeker_jobapplications_jobseeker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplications',
            old_name='jobSeeker_name',
            new_name='jobSeeker',
        ),
    ]
